In [1]:
import numpy as np
import pandas as pd
s1 = pd.Series(np.random.rand(4))
s2 = pd.Series(np.random.rand(4))
s3 = pd.Series(np.random.rand(4))
s4 = pd.Series(np.random.rand(4))

In [2]:
df = pd.DataFrame([s1,s2,s3,s4])

In [3]:
df.columns = ['Random_value_1','Random_value_2','Random_value_3','Random_value_4']

In [4]:
df.describe( )

       Random_value_1  Random_value_2  Random_value_3  Random_value_4
count        4.000000        4.000000        4.000000        4.000000
mean         0.798677        0.397730        0.433538        0.429420
std          0.123269        0.212555        0.070448        0.373499
min          0.683077        0.231096        0.393834        0.029108
25%          0.713143        0.236741        0.397480        0.194654
50%          0.776568        0.338988        0.400622        0.399556
75%          0.862102        0.499977        0.436680        0.634323
max          0.958493        0.681849        0.539074        0.889462

In [5]:
df.isnull( )

   Random_value_1  Random_value_2  Random_value_3  Random_value_4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

In [6]:
df. info( )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random_value_1  4 non-null      float64
 1   Random_value_2  4 non-null      float64
 2   Random_value_3  4 non-null      float64
 3   Random_value_4  4 non-null      float64
dtypes: float64(4)
memory usage: 256.0 bytes

In [7]:
df['Random_value_1'].dtype
df['Random_value_2'].dtype
df['Random_value_3'].dtype
df['Random_value_4'].dtype

dtype('float64')

In [8]:
df.loc[0:3,'Random_value_2':'Random_value_3']

   Random_value_2  Random_value_3
0        0.238622        0.393834
1        0.681849        0.398695
2        0.439353        0.402549
3        0.231096        0.539074

In [9]:
df.iloc[0:4,1:3]

   Random_value_2  Random_value_3
0        0.238622        0.393834
1        0.681849        0.398695
2        0.439353        0.402549
3        0.231096        0.539074